# language
language: java

# version numbers
jdk:
  - oraclejdk8

script:
  - jdk_switcher use oraclejdk8

before_install:
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

install: mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
