# language
language: java

# version numbers
jdk:
  - oraclejdk8

script:
  - jdk_switcher use oraclejdk8

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle

after_success:
  - bash <(curl -s https://codecov.io/bash)
