# language
language: java

# version numbers
jdk:
  - oraclejdk8

addons:
  sonarqube: true

env:
  global:
    - secure:

script:
  - jdk_switcher use oraclejdk8
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=7a81b254c38b9f12d58ca9657be0c28d3e64baa1

before_install:
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

install: mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
