# language
language: java

# version numbers
jdk:
  - oraclejdk8

before_install:
  - apt-get update
  - apt-get install -y maven

before_script:
   - update-alternatives --set java $java_path
   - java -version

after_success:
  - bash <(curl -s https://codecov.io/bash)
